# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

#MyDomoAtHome specific configuration
domo_path: "http://192.168.0.10:8080"
domo_db: "/home/in/test/testenv/domoticz.db"
external_url_camera : "http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=&pwd="
volumio_path: ""

# Your application's name
appname: "MyDomoAtHome"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: UTF-8
engines:
    serializer:
        JSON:
            utf8: 0


