log: 'warning'
startup_info: 0
show_errors:  0
domo_path: "http://127.0.0.1:8080"
domo_db: "/home/in/test/testenv/domoticz.db"
appname: "MyDomoAtHome REST Gateway"
charset: "UTF-8"
engines:
    serializer:
        JSON:
            utf8: 0
